### PR TITLE
Proper-case primitive from DocuSign API causes fatal error

### PR DESCRIPTION
**Pull request by trickeyone**
Proper-case primitive returned from DocuSign API causes fatal error
```
Fatal Error (1): Class 'Number' not found in [/path/to/app/vendor/docusign/esign-client/src/ObjectSerializer.php, line 274]
```

Also fixed the call to `santitizeFilename` not being called via instance or static call at line 261 by setting method to static and calling staticly.

### CODE REVIEW

**Comment by benburleson** [comment]
Oh nice, this probably makes my PR unnecessary: https://github.com/docusign/docusign-php-client/pull/46

**Comment by JeffreyHyer** [comment]
What's the best way to handle other missing field types? After applying this patch I get an error about DateTime being an invalid type. After I create a Model for that I get an error about 'array' being an invalid type. I feat this is a rabbit hole of endless missing types. Am I missing something? Is there an easier way to fix this than creating new models for the missing types?

**Comment by northern** [comment]
We also have these problems and they are a show stopper for us. Can these changes please be accepted, merged and released?

Thanks in advance!

**Comment by trickeyone** [comment]
Could we get a response on these pull requests? There are some that have been open since 2016.

**Comment by ccorliss** [comment]
@trickeyone Why are there seemingly unrelated changes here - like SSL changes?  

Might be a reason why this hasn't been merged yet.

**Comment by trickeyone** [comment]
@ccorliss Those are in relation to #57, per my last comment. And those were recent changes, so no, that's not why it hasn't been merged.

**Comment by ccorliss** [comment]
@gsnavin can you help merge this please? Thanks

**Comment by trickeyone** [comment]
@ccorliss @gsnavin Any update on this? This is a major blocker due to errors like this:
```
Class 'Number' not found {"exception":"[object] (Error(code: 0): Class 'Number' not found at /path/to/app/app/vendor/docusign/esign-client/src/ObjectSerializer.php:274)
[stacktrace]
#0 /path/to/app/app/vendor/docusign/esign-client/src/ObjectSerializer.php(291): DocuSign\\eSign\\ObjectSerializer::deserialize(1, 'Number', NULL)
#1 /path/to/app/app/vendor/docusign/esign-client/src/ObjectSerializer.php(236): DocuSign\\eSign\\ObjectSerializer::deserialize(Object(stdClass), '\\\\DocuSign\\\\eSign...', NULL)
#2 /path/to/app/app/vendor/docusign/esign-client/src/ObjectSerializer.php(291): DocuSign\\eSign\\ObjectSerializer::deserialize(Array, '\\\\DocuSign\\\\eSign...', NULL)
#3 /path/to/app/app/vendor/docusign/esign-client/src/ObjectSerializer.php(291): DocuSign\\eSign\\ObjectSerializer::deserialize(Object(stdClass), '\\\\DocuSign\\\\eSign...', NULL)
#4 /path/to/app/app/vendor/docusign/esign-client/src/ObjectSerializer.php(236): DocuSign\\eSign\\ObjectSerializer::deserialize(Object(stdClass), '\\\\DocuSign\\\\eSign...', NULL)
#5 /path/to/app/app/vendor/docusign/esign-client/src/ObjectSerializer.php(291): DocuSign\\eSign\\ObjectSerializer::deserialize(Array, '\\\\DocuSign\\\\eSign...', NULL)
#6 /path/to/app/app/vendor/docusign/esign-client/src/Api/EnvelopesApi.php(7670): DocuSign\\eSign\\ObjectSerializer::deserialize(Object(stdClass), '\\\\DocuSign\\\\eSign...', Array)
#7 /path/to/app/app/vendor/docusign/esign-client/src/Api/EnvelopesApi.php(7574): DocuSign\\eSign\\Api\\EnvelopesApi->listRecipientsWithHttpInfo('1225104', '513d9084-9b0f-4...', Object(DocuSign\\eSign\\Api\\EnvelopesApi\\ListRecipientsOptions))

```

**Comment by trickeyone** [comment]
So, it's been almost another year. Can we get an update on if this is going to be merged into 4.x or 5.x?

**Comment by trickeyone** [comment]
Closing in favor of updated #180 since this PR is well over 5 years old. Hoping the new PR with a single change will be merged to correct this issue.

**Pull request closed without merging**
